### ISSUE TITLE
Concept

### ISSUE THREAD

**Issue by LucasDenduyver** [LucasDenduyver/MHP#1]
Zelf ben ik meer into concept 1 maar misschien hebben jullie nog tips of aanpassingen om een concept nog beter/uitdagender te maken?

Readme in develop branch

**Comment by benoitboucart** [comment]
Je kan zeker verder met concept 1. Basisconcept is op zich wel ok, maar ik mis uitleg over de technische zaken.

Hoe zal bericht gedeeld kunnen worden? Elk bericht kan je via specifieke URL zien? Wat wordt er getoond? etc.

En welke nieuwe/ongeziene technologie ga je implementeren?
Welke services ga je gebruiken? Welke stack? Nextjs +....? Check de opdrachtfiche voor meer duiding.
Dit is nl. ook een belangrijk deel van de opdracht.

Succes!
